# Generated by Django 5.2.2 on 2025-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_barre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
