# Generated by Django 5.2.2 on 2025-06-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_code_barre_product_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code_barre',
        ),
        migrations.AddField(
            model_name='product',
            name='price_v',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
