# Generated by Django 5.2.2 on 2026-04-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_achat_achatitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reference',
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='app.product')),
            ],
        ),
    ]
