# Generated by Django 5.2.2 on 2026-04-24 09:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_achatitem_price_snapshot_orderitem_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatitem',
            name='price_v_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
